version: '3'

services:
  wordpress:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 80:80
    
  db:
    image: mysql:8.0.32
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
volumes:
  db:
  wordpress:
