version: '3.9'

services:
  wordpress:
  # For test use latest WP image
    image: wordpress
  # Attach local folder
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    depends_on:
      - db
  # Use envs from file
    env_file:
      - .env
  # Bind port
    ports:
      - 80:80
    
  db:
  # For test use mysql:8.0.32
    image: mysql:8.0.32
    restart: always
  # Attach db to local folder
    volumes:
      - ./db:/var/lib/mysql
  # Use envs from file
    env_file:
      - .env
  
  jenkins:
    image: jenkins:mysql_client
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - ./Jenkins-container:/var/jenkins_home
      - ./wordpress:/home/wordpress
    restart: on-failure
    links:
      - db
      - wordpress

volumes:
  db:
  wordpress:
  Jenkins-container:
